[package]
name = "rtspy-controller"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
hyper = "1.8.1"
opencv = { version = "0.98.1" }
serde = { version = "1.0.228", features=["derive"] }
serde_json = "1.0.149"
tokio = { version="1.49.0", features=["full"] }
